[package]
name = "scrumbot"
version = "0.1.0"
authors = ["matthewperry <matthew.perry@arcticshores.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slack = "0.22.0"
